#
# Format:
#
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#

production:
  app: divi-service
  stack: cedar
  repo: git@heroku.personal:divi-service.git
  config:
    BUNDLE_WITHOUT: "development:test"
    GOOGLE_ANALYTICS: "UA-12345678-1"
    ERRBIT_TOKEN: '600e99f0af40e46a999cc4db2d30c511'

staging:
  stack: cedar
  app: divi-staging
  repo: git@heroku.personal:divi-staging.git
  config: &default
    BUNDLE_WITHOUT: "development:test"
    ERRBIT_TOKEN: 'ba4df5c987e04fbf9c4caa65efeb6479'

# demo:
#   app: awesomeapp-demo
#   config: *default
