#
# Format:
#
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#

defaults: &defaults
  app: divi-service
  stack: cedar
  #repo: git@heroku.personal:divi-service.git
  config:
    BUNDLE_WITHOUT:         'development:test'
    GOOGLE_ANALYTICS:       'UA-12345678-1'
    ERRBIT_TOKEN:           'ba4df5c987e04fbf9c4caa65efeb6479'
    NEW_RELIC_APP_NAME:     'divi-service'
    SECRET_KEY_BASE:        '5e632f8b8b4f74e25c7b9103fb21ea3b14245b461a21510c1c32cc9635ca234d940532c9f8af0f1717faa8febf83590de40c947b5b5ca1fff825235e638819ed'

    AWS_ACCESS_KEY_ID:      'AKIAITYWUGKIHBHP4YGQ'
    AWS_SECRET_ACCESS_KEY:  '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'
    BUILDPACK_URL:          'https://github.com/heroku/heroku-buildpack-ruby'
    NEW_RELIC_APP_NAME:     'divi-service'
    NEW_RELIC_LICENSE_KEY:  'def31abb37488c95123da3df926af42f6db47867'
    NEW_RELIC_LOG:          'stdout'
    PUBNUB_PUBLISH_KEY:     'pub-c-92cb1e82-71a1-4fd0-81ed-8cce0f25e4a3'
    PUBNUB_SUBSCRIBE_KEY:   'sub-c-56e5356a-5071-11e3-98c1-02ee2ddab7fe'
    S3_BUCKET:              'divi-content-playstore'
    WEB_CONCURRENCY:        1
  addons: &addons
    - newrelic:stark
    - pgbackups:plus
    - scheduler:standard
    - heroku-postgresql:hobby-dev
    - logentries:tryit

production:
  <<: *defaults
  addons:
    - *addons
    - heroku-postgresql:standard-0
admin:
  <<: *defaults
  app: divi-admin
  #repo: git@heroku.personal:divi-admin.git
  config:
    SECRET_KEY_BASE:        '9a30e1238971c0398b8e93b8519522f7794f536eb0d72a417e0e988b3590de8444e1c2520798099de8af047ff2c4dd7ae77959ff81c51fd1a3f4ed0d2b5f1463'
playstore:
  <<: *defaults
  app: divi-playstore
  #repo: git@heroku.personal:divi-service.git
  config:
    SECRET_KEY_BASE:        'cfe4950846741e9e8278215bc39811a5ea323ffa5feb9a420219649f576759e6cd855899efa70974093f673302dbf6f4c0b550bc0ca3888ecd3ad4ad80e37b18'
staging:
  <<: *defaults
  app: divi-staging
  #repo: git@heroku.personal:divi-staging.git
  config:
    ERRBIT_TOKEN:           '600e99f0af40e46a999cc4db2d30c511'
    SECRET_KEY_BASE:        '83026357c50fa5fdc9cd13e1020e1179fba7b126db8ffd181d00b4caa488d9184e6ead09e56ebee71cb8b0bbfef12bd1f67747f50c5b698b23caf975ecf3500f'
