#
# Format:
#
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#

admin: &default
  app: divi-admin
  #repo: git@heroku.personal:divi-admin.git
  config: &default_config
    AWS_ACCESS_KEY_ID:      "AKIAITYWUGKIHBHP4YGQ"
    AWS_SECRET_ACCESS_KEY:  "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"
    S3_BUCKET:              "divi-content-prod"
    BUNDLE_WITHOUT:         "development:test"
    GOOGLE_ANALYTICS:       "UA-12345678-1"
    ERRBIT_TOKEN:           'ba4df5c987e04fbf9c4caa65efeb6479'
    NEW_RELIC_APP_NAME:     'divi-service'
    SECRET_KEY_BASE:        '5e632f8b8b4f74e25c7b9103fb21ea3b14245b461a21510c1c32cc9635ca234d940532c9f8af0f1717faa8febf83590de40c947b5b5ca1fff825235e638819ed'
  addons: &default_addons
    - newrelic:stark
    - pgbackups:plus
    - scheduler:standard

staging-admin:
  <<: *default
  app: divi-staging-admin
  config:
    <<: *default_config
    S3_BUCKET:              "divi-content-staging"
    SECRET_KEY_BASE:        'd7cb8463b04bba15282457c2f5f8309296e065e711996463a9ab93748253db08aeab1c98bf1ae288e958e18ca0c7a99bf29532417ddefc180abb0997f1c66cdf'

dev-admin:
  <<: *default
  app: divi-dev-admin
  config:
    <<: *default_config
    S3_BUCKET:              "divi-content-dev"
    SECRET_KEY_BASE:        'a8472fd577a9dcd8b066e77d48bab76164717da4fa0b45a98330292c66f828ea63314a1dff0305fc224fc01f61c784101353f8691fcd789a480d86b44371e759'

seed:
  <<: *default
  app: divi-seed
  config:
    <<: *default_config
    S3_BUCKET:              "divi-content-seed"
    SECRET_KEY_BASE:        '329988c552c240b0a79196aa6272caf3dcf10eb0206b20e2d415e0deabdac52b3330e3baf4c9b8c05c64b672f82026e7cf23b3adec4578c8b0e43d67313ad98a'
